#!/usr/bin/python

import getopt, sys

'''
Thanks for your interest! I look forward to getting to know you
'''
def main():
    opts, args = getopt.getopt(sys.argv[1:], "ncalm", 
        ["name", "contact", "about", "links", "misc"])
    try:
        for opt, arg in opts:
            if opt in ("-n", "--name"):
                print "Andrea Fey"
            elif opt in ("-c", "--contact"):
                print "andrea.fey at gmail.com  |  828.243.7502"
            elif opt in ("-e", "--experience"):
                print experience()
            elif opt in ("-l", "--links"):
                print "github.com/andreafey  |  linkedin.com/andreafey314159"
            elif opt in ("-m", "--misc"):
                print unicode(u"rhymes with \u03C0")
            elif opt in ("-a", "--me"):
                print "something"

def usage():
    print '''Usage:
    
def name():
    return "Andrea Fey"

def contact():
    return "andrea.fey at gmail.com  |  828.423.0331"
def experience():
    return {'Java': 8.0, 'Scala': 0.5, 'Oracle': 7.5, 'Python': 2.0}

if __name__ == "__main__":
    sys.exit(main())
