#!/usr/bin/python

import getopt, sys

'''
Find out more about me
'''
def main():
    opts, args = getopt.getopt(sys.argv[1:], "anclem", 
        ["me", "name", "contact", "links", "experience", "misc"])
    if ('--me','') in opts or ('-a','') in opts:
        opts = zip(['-n','-c','-l','-e','-m'], [''] * 6)
    elif (len(opts) < 1):
        usage()
    try:
        for opt, arg in opts:
            if opt in ("-n", "--name"):
                print "Andrea Fey"
            elif opt in ("-c", "--contact"):
                print "andrea.fey@gmail.com  ||  828.243.7502"
            # experience in years
            elif opt in ("-e", "--experience"):
                print { 'Scala': 2.11.7, 'PostgreSQL': 9.4.4, 'Java': 8.0, 'Backbone': 1.2.1, 'Python': 2.7 }
            elif opt in ("-l", "--links"):
                print "www.andreafey.com  |  github.com/andreafey  |  @rhymmespi  |  linkedin.com/andreafey314159"
            elif opt in ("-m", "--misc"):
                print unicode(u"rhymes with \u03C0")
    except Exception:
        usage()

def usage():
    print '''Usage:
        contact --me   find out more about me
        '''

if __name__ == "__main__":
    sys.exit(main())
